# Generated by Django 5.0.7 on 2025-12-09 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_bookinstance_borrower'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['-due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
    ]
